apiVersion: keyvault.azure.crossplane.io/v1alpha1
kind: KeyVaultSecret
metadata:
  name: example
spec:
  forProvider:
    vaultBaseUrl: 'https://kv-crossplane-secrets.vault.azure.net/'
    name: crossplane-test-secret
    value: crossplane-test-secret-value
    contentType: text/plain
    tags:
      created_by: crossplane
  providerConfigRef:
    name: example